/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTraceRouteImport } from './routes/dashboard.trace'
import { Route as DashboardMomentRouteImport } from './routes/dashboard.moment'
import { Route as DashboardEdgeClockRouteImport } from './routes/dashboard.edge-clock'
import { Route as DashboardDivergenceRouteImport } from './routes/dashboard.divergence'
import { Route as DashboardCollisionRouteImport } from './routes/dashboard.collision'
import { Route as DashboardChangeQueueRouteImport } from './routes/dashboard.change-queue'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTraceRoute = DashboardTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.trace.lazy').then((d) => d.Route),
)
const DashboardMomentRoute = DashboardMomentRouteImport.update({
  id: '/moment',
  path: '/moment',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.moment.lazy').then((d) => d.Route),
)
const DashboardEdgeClockRoute = DashboardEdgeClockRouteImport.update({
  id: '/edge-clock',
  path: '/edge-clock',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.edge-clock.lazy').then((d) => d.Route),
)
const DashboardDivergenceRoute = DashboardDivergenceRouteImport.update({
  id: '/divergence',
  path: '/divergence',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.divergence.lazy').then((d) => d.Route),
)
const DashboardCollisionRoute = DashboardCollisionRouteImport.update({
  id: '/collision',
  path: '/collision',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.collision.lazy').then((d) => d.Route),
)
const DashboardChangeQueueRoute = DashboardChangeQueueRouteImport.update({
  id: '/change-queue',
  path: '/change-queue',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard.change-queue.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/change-queue': typeof DashboardChangeQueueRoute
  '/dashboard/collision': typeof DashboardCollisionRoute
  '/dashboard/divergence': typeof DashboardDivergenceRoute
  '/dashboard/edge-clock': typeof DashboardEdgeClockRoute
  '/dashboard/moment': typeof DashboardMomentRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/change-queue': typeof DashboardChangeQueueRoute
  '/dashboard/collision': typeof DashboardCollisionRoute
  '/dashboard/divergence': typeof DashboardDivergenceRoute
  '/dashboard/edge-clock': typeof DashboardEdgeClockRoute
  '/dashboard/moment': typeof DashboardMomentRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/change-queue': typeof DashboardChangeQueueRoute
  '/dashboard/collision': typeof DashboardCollisionRoute
  '/dashboard/divergence': typeof DashboardDivergenceRoute
  '/dashboard/edge-clock': typeof DashboardEdgeClockRoute
  '/dashboard/moment': typeof DashboardMomentRoute
  '/dashboard/trace': typeof DashboardTraceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/dashboard/change-queue'
    | '/dashboard/collision'
    | '/dashboard/divergence'
    | '/dashboard/edge-clock'
    | '/dashboard/moment'
    | '/dashboard/trace'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard/change-queue'
    | '/dashboard/collision'
    | '/dashboard/divergence'
    | '/dashboard/edge-clock'
    | '/dashboard/moment'
    | '/dashboard/trace'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/dashboard/change-queue'
    | '/dashboard/collision'
    | '/dashboard/divergence'
    | '/dashboard/edge-clock'
    | '/dashboard/moment'
    | '/dashboard/trace'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trace': {
      id: '/dashboard/trace'
      path: '/trace'
      fullPath: '/dashboard/trace'
      preLoaderRoute: typeof DashboardTraceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/moment': {
      id: '/dashboard/moment'
      path: '/moment'
      fullPath: '/dashboard/moment'
      preLoaderRoute: typeof DashboardMomentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/edge-clock': {
      id: '/dashboard/edge-clock'
      path: '/edge-clock'
      fullPath: '/dashboard/edge-clock'
      preLoaderRoute: typeof DashboardEdgeClockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/divergence': {
      id: '/dashboard/divergence'
      path: '/divergence'
      fullPath: '/dashboard/divergence'
      preLoaderRoute: typeof DashboardDivergenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collision': {
      id: '/dashboard/collision'
      path: '/collision'
      fullPath: '/dashboard/collision'
      preLoaderRoute: typeof DashboardCollisionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/change-queue': {
      id: '/dashboard/change-queue'
      path: '/change-queue'
      fullPath: '/dashboard/change-queue'
      preLoaderRoute: typeof DashboardChangeQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChangeQueueRoute: typeof DashboardChangeQueueRoute
  DashboardCollisionRoute: typeof DashboardCollisionRoute
  DashboardDivergenceRoute: typeof DashboardDivergenceRoute
  DashboardEdgeClockRoute: typeof DashboardEdgeClockRoute
  DashboardMomentRoute: typeof DashboardMomentRoute
  DashboardTraceRoute: typeof DashboardTraceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChangeQueueRoute: DashboardChangeQueueRoute,
  DashboardCollisionRoute: DashboardCollisionRoute,
  DashboardDivergenceRoute: DashboardDivergenceRoute,
  DashboardEdgeClockRoute: DashboardEdgeClockRoute,
  DashboardMomentRoute: DashboardMomentRoute,
  DashboardTraceRoute: DashboardTraceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
