-- ============================================================================
-- MARCOVAULT · Signal History — server recorder storage (Phase 3, Step B)
--
-- Private schemas only. NONE of history / engine / ops may be added to the
-- Supabase Data API "Exposed schemas" list. The browser has no path to any of
-- this: no grants to anon / authenticated / public.
--
--   history  durable product data (events, episodes, resolved outcomes) and
--            the operational round / gap log (30-day retention)
--   engine   temporary engine state (snapshots 90 min, pending outcomes,
--            provider cooldowns) — never read as Signal History
--   ops      read-only operational truth (status / health) + housekeeping
--
-- Times are timestamptz; the recorder model uses epoch milliseconds and the
-- adapter converts exactly with engine.ms_to_ts / engine.ts_to_ms.
--
-- Roles: recorder_writer (the recorder Edge Function) and recorder_reader (the
-- health Edge Function) are created NOLOGIN. Giving them a password / LOGIN is
-- a B0 provisioning step done by the owner; no credential is in this file.
-- ============================================================================

create schema if not exists history;
create schema if not exists engine;
create schema if not exists ops;

-- ---------------------------------------------------------------------------
-- Exact epoch-millisecond conversion (integer arithmetic, no float rounding)
-- ---------------------------------------------------------------------------
create or replace function engine.ms_to_ts(ms bigint) returns timestamptz
  language sql immutable strict parallel safe
  as $$ select timestamptz 'epoch' + ms * interval '1 millisecond' $$;

create or replace function engine.ts_to_ms(ts timestamptz) returns bigint
  language sql immutable strict parallel safe
  as $$ select (extract(epoch from ts) * 1000)::bigint $$;

-- Immutability guard for insert-only tables (applies even to privileged roles).
create or replace function engine.reject_mutation() returns trigger
  language plpgsql
  as $$
begin
  raise exception '% on %.% is not allowed: rows are immutable', tg_op, tg_table_schema, tg_table_name
    using errcode = 'restrict_violation';
end
$$;

-- ---------------------------------------------------------------------------
-- history.signal_round — round / claim / GAP log (operational, 30 days)
-- ---------------------------------------------------------------------------
create table history.signal_round (
  key            text primary key,                        -- scheduled minute, e.g. 2026-09-26T00:07Z
  scheduled_at   timestamptz not null unique,
  state          text not null check (state in ('CLAIMED','COMPLETED','FAILED','GAP','SUPERSEDED')),
  attempt        smallint not null check (attempt >= 0),
  owner          text,
  lease_until    timestamptz,
  data_status    text check (data_status in ('live','degraded','stale','offline')),
  rules_version  text,
  universe_size  smallint,
  issues         text[] not null default '{}',
  -- 7 endpoints (engine ENDPOINTS order) × [attempts, ok, failed, rateLimited, skipped]
  requests       smallint[] check (requests is null or cardinality(requests) = 35),
  started_at     timestamptz,                             -- when the current claim was taken
  finished_at    timestamptz,
  duration_ms    integer generated always as (
                   case when started_at is not null and finished_at is not null
                        then (extract(epoch from (finished_at - started_at)) * 1000)::integer end
                 ) stored,
  check (scheduled_at = date_trunc('minute', scheduled_at)),
  -- a GAP was never observed: it carries no values at all
  check (state <> 'GAP' or (owner is null and data_status is null and rules_version is null
                            and universe_size is null and requests is null and cardinality(issues) = 0))
);

-- ---------------------------------------------------------------------------
-- history.signal_event — IMMUTABLE durable event
-- ---------------------------------------------------------------------------
create table history.signal_event (
  id             text primary key,                        -- deterministic evt_ id from the recorder
  asset_key      text not null,
  chain_id       text not null,
  address        text not null,                           -- original token address (case preserved)
  pair_address   text not null,                           -- the exact captured pair
  symbol         text,
  type           text not null check (type in ('EARLY_MOMENTUM','LIQUIDITY_ADDED','LIQUIDITY_REMOVED')),
  severity       text check (severity in ('MEDIUM','HIGH')),
  rules_version  text not null,                           -- exactly as generated by the recorder
  opened_round   timestamptz not null,                    -- SCHEDULER identity (scheduled minute)
  opened_at      timestamptz not null,                    -- REAL provider observation time
  evidence       jsonb not null,                          -- the engine's own rule object
  open_snapshot  jsonb not null,                          -- compact selected real fields
  check (opened_round = date_trunc('minute', opened_round))
);
create index signal_event_feed  on history.signal_event (opened_at desc);
create index signal_event_asset on history.signal_event (asset_key, opened_at desc);
create trigger signal_event_immutable before update or delete on history.signal_event
  for each row execute function engine.reject_mutation();

-- ---------------------------------------------------------------------------
-- history.signal_episode — NARROW mutable lifecycle state (HOT-update friendly:
-- no per-round column is indexed; fillfactor leaves room on the page)
-- ---------------------------------------------------------------------------
create table history.signal_episode (
  event_id                    text primary key references history.signal_event,
  asset_key                   text not null,
  type                        text not null check (type in ('EARLY_MOMENTUM','LIQUIDITY_ADDED','LIQUIDITY_REMOVED')),
  rules_version               text not null,
  status                      text not null check (status in ('OPEN','CLOSED')),
  close_reason                text check (close_reason in ('SIGNAL_EXIT','TRACKING_LOST','RULES_CHANGED')),
  closed_at                   timestamptz,
  last_fired_at               timestamptz not null,
  last_valid_at               timestamptz not null,
  last_evaluated_at           timestamptz not null,      -- round-order guard / CAS token
  negative_streak_count       smallint not null default 0,
  negative_streak_started_at  timestamptz,
  last_valid_negative_at      timestamptz,
  rounds_fired                integer not null default 1,
  peak_va_ratio               double precision,
  peak_abs_liquidity_delta    double precision,
  check ((status = 'OPEN') = (close_reason is null)),
  check ((status = 'OPEN') = (closed_at is null))
) with (fillfactor = 70);
-- At most one OPEN episode per (asset, signal type).
create unique index signal_episode_one_open on history.signal_episode (asset_key, type) where status = 'OPEN';

-- ---------------------------------------------------------------------------
-- history.signal_outcome — RESOLVED outcomes only, INSERT-ONLY
-- (PENDING bookkeeping lives in engine.pending_outcome and is deleted on
-- resolution). Market columns are the benchmarked selection of the compact
-- snapshot; the event's open_snapshot keeps the full compact set.
-- ---------------------------------------------------------------------------
create table history.signal_outcome (
  event_id            text not null references history.signal_event,
  horizon_minutes     smallint not null check (horizon_minutes in (5, 15, 60, 240, 1440)),
  availability        text not null check (availability in ('OBSERVED','UNAVAILABLE')),
  unavailable_reason  text check (unavailable_reason in
                        ('WINDOW_ELAPSED','PROVIDER_ERROR','RATE_LIMITED','PAIR_NOT_RETURNED','BUDGET_DEFERRED')),
  target_at           timestamptz not null,
  window_end_at       timestamptz not null,
  observed_at         timestamptz,                        -- the real sample time
  delay_seconds       integer,
  source              text check (source in ('ROUND','DUE_TOKEN_BATCH','PAIR_FALLBACK')),
  round_at            timestamptz,                        -- set when source = ROUND
  pair_address        text,                               -- the exact captured pair (audit)
  price_usd           double precision,
  liquidity_usd       double precision,
  fdv                 double precision,
  market_cap          double precision,
  volume_h1           double precision,
  volume_h24          double precision,
  txns_h1_buys        integer,
  txns_h1_sells       integer,
  price_change_h1     double precision,
  attempts            smallint not null,
  primary key (event_id, horizon_minutes),
  check (window_end_at >= target_at),
  -- directional acceptance rule as a database invariant
  check (availability <> 'OBSERVED' or (observed_at is not null and source is not null
         and pair_address is not null and observed_at between target_at and window_end_at
         and unavailable_reason is null)),
  check (availability <> 'UNAVAILABLE' or (observed_at is null and unavailable_reason is not null))
);
create trigger signal_outcome_immutable before update or delete on history.signal_outcome
  for each row execute function engine.reject_mutation();

-- ---------------------------------------------------------------------------
-- engine.* — TEMPORARY engine state (never Signal History)
-- ---------------------------------------------------------------------------
create table engine.snapshot_round (
  key           text primary key,
  scheduled_at  timestamptz not null,                     -- the round's scheduled minute
  snapshots     jsonb not null                            -- PairSnapshot[]; each keeps its real observedAt
) with (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 20,
        toast.autovacuum_vacuum_scale_factor = 0, toast.autovacuum_vacuum_threshold = 20);
create index snapshot_round_scheduled on engine.snapshot_round (scheduled_at);

create table engine.pending_outcome (
  event_id         text not null references history.signal_event,
  horizon_minutes  smallint not null check (horizon_minutes in (5, 15, 60, 240, 1440)),
  target_at        timestamptz not null,
  window_end_at    timestamptz not null,
  last_failure     text check (last_failure in
                     ('WINDOW_ELAPSED','PROVIDER_ERROR','RATE_LIMITED','PAIR_NOT_RETURNED','BUDGET_DEFERRED')),
  attempts         smallint not null default 0,
  primary key (event_id, horizon_minutes)
) with (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 20);
create index pending_outcome_target on engine.pending_outcome (target_at);

create table engine.provider_cooldown (
  endpoint         text primary key check (endpoint in
                     ('BOOST_LATEST','BOOST_TOP','ADS','CANONICAL_PAIR','TOKEN_ENRICHMENT','DUE_TOKEN_BATCH','PAIR_FALLBACK')),
  until            timestamptz not null,
  consecutive_429  smallint not null
);

-- ---------------------------------------------------------------------------
-- ops.* — operational truth
-- ---------------------------------------------------------------------------
-- Invocation counters (includes SKIPPED / unauthorized calls that never reach a
-- round row). One row per (day, result): cheap HOT updates, 30-day retention.
create table ops.invocation_daily (
  day     date not null,
  result  text not null,
  count   integer not null default 0,
  primary key (day, result)
) with (fillfactor = 70);

-- Endpoint order used by history.signal_round.requests (must equal the
-- recorder's ENDPOINTS constant — asserted by the integration tests).
create or replace function ops.endpoints() returns text[]
  language sql immutable parallel safe
  as $$ select array['BOOST_LATEST','BOOST_TOP','ADS','CANONICAL_PAIR','TOKEN_ENRICHMENT','DUE_TOKEN_BATCH','PAIR_FALLBACK'] $$;

-- Sum one counter (1 attempts, 2 ok, 3 failed, 4 rateLimited, 5 skipped) over all endpoints.
create or replace function ops.request_total(requests smallint[], counter integer) returns integer
  language sql immutable parallel safe
  as $$ select coalesce(sum(requests[e * 5 + counter]), 0)::integer from generate_series(0, 6) as e $$;

-- Full operational status at a given instant (a view below evaluates it at now()).
create or replace function ops.recorder_status_at(at timestamptz) returns jsonb
  language sql stable security definer set search_path = ''
  as $$
  with r as (select * from history.signal_round),
  d24 as (select * from r where scheduled_at > at - interval '24 hours' and scheduled_at <= at),
  d60 as (select * from r where scheduled_at > at - interval '60 minutes' and scheduled_at <= at),
  rl as (
    select e.name, coalesce(sum(d.requests[(e.i - 1) * 5 + 4]), 0)::integer as rate_limited
    from unnest(ops.endpoints()) with ordinality as e(name, i)
    left join d24 d on d.requests is not null
    group by e.name, e.i order by e.i
  ),
  hz as (
    select h.horizon,
      (select count(*) from history.signal_outcome o where o.horizon_minutes = h.horizon and o.availability = 'OBSERVED') as observed,
      (select count(*) from history.signal_outcome o where o.horizon_minutes = h.horizon and o.availability = 'UNAVAILABLE') as unavailable,
      (select count(*) from engine.pending_outcome p where p.horizon_minutes = h.horizon) as pending
    from unnest(array[5, 15, 60, 240, 1440]) as h(horizon)
  )
  select jsonb_build_object(
    'at', at,
    'last_scheduled_round', (select max(scheduled_at) from r where state <> 'GAP' and scheduled_at <= at),
    'last_completed_round', (select max(scheduled_at) from r where state = 'COMPLETED' and scheduled_at <= at),
    'last_completed_finished_at', (select max(finished_at) from r where state = 'COMPLETED' and finished_at <= at),
    'last_failed_round', (select max(scheduled_at) from r where state = 'FAILED' and scheduled_at <= at),
    'rounds_60m', (select jsonb_build_object(
        'completed', count(*) filter (where state = 'COMPLETED'),
        'failed', count(*) filter (where state = 'FAILED'),
        'gap', count(*) filter (where state = 'GAP'),
        'superseded', count(*) filter (where state = 'SUPERSEDED'),
        'claimed', count(*) filter (where state = 'CLAIMED')) from d60),
    'rounds_24h', (select jsonb_build_object(
        'completed', count(*) filter (where state = 'COMPLETED'),
        'failed', count(*) filter (where state = 'FAILED'),
        'gap', count(*) filter (where state = 'GAP'),
        'superseded', count(*) filter (where state = 'SUPERSEDED'),
        'claimed', count(*) filter (where state = 'CLAIMED')) from d24),
    'abandoned_claims', (select count(*) from r where state = 'CLAIMED' and lease_until < at),
    'lease_takeovers_24h', (select count(*) from d24 where attempt > 1),
    'duration_ms_24h', (select jsonb_build_object(
        'p50', percentile_cont(0.5) within group (order by duration_ms),
        'p95', percentile_cont(0.95) within group (order by duration_ms),
        'max', max(duration_ms)) from d24 where state = 'COMPLETED'),
    'last_provider_success', (select max(scheduled_at) from r
        where requests is not null and ops.request_total(requests, 2) > 0 and scheduled_at <= at),
    'last_rate_limited', (select max(scheduled_at) from r
        where requests is not null and ops.request_total(requests, 4) > 0 and scheduled_at <= at),
    'rate_limited_24h_by_endpoint', (select jsonb_object_agg(name, rate_limited) from rl),
    'requests_24h', (select jsonb_build_object(
        'attempts', coalesce(sum(ops.request_total(requests, 1)), 0),
        'ok', coalesce(sum(ops.request_total(requests, 2)), 0),
        'failed', coalesce(sum(ops.request_total(requests, 3)), 0),
        'rate_limited', coalesce(sum(ops.request_total(requests, 4)), 0),
        'skipped', coalesce(sum(ops.request_total(requests, 5)), 0)) from d24 where requests is not null),
    'database_bytes', pg_database_size(current_database()),
    'signal_history_bytes', (select coalesce(sum(pg_total_relation_size(c.oid)), 0)
        from pg_class c join pg_namespace n on n.oid = c.relnamespace
        where n.nspname in ('history', 'engine', 'ops') and c.relkind in ('r', 'p')),
    'events_total', (select count(*) from history.signal_event),
    'events_by_type_7d', (select coalesce(jsonb_object_agg(k, v), '{}'::jsonb) from (
        select (opened_at at time zone 'UTC')::date || ' ' || type as k, count(*) as v
        from history.signal_event where opened_at > at - interval '7 days' and opened_at <= at
        group by 1) x),
    'open_episodes', (select count(*) from history.signal_episode where status = 'OPEN'),
    'closed_by_reason', (select jsonb_build_object(
        'SIGNAL_EXIT', count(*) filter (where close_reason = 'SIGNAL_EXIT'),
        'TRACKING_LOST', count(*) filter (where close_reason = 'TRACKING_LOST'),
        'RULES_CHANGED', count(*) filter (where close_reason = 'RULES_CHANGED')) from history.signal_episode),
    'outcomes', jsonb_build_object(
        'pending', (select count(*) from engine.pending_outcome),
        'due', (select count(*) from engine.pending_outcome where target_at <= at),
        'observed', (select count(*) from history.signal_outcome where availability = 'OBSERVED'),
        'unavailable', (select count(*) from history.signal_outcome where availability = 'UNAVAILABLE')),
    'outcome_coverage_by_horizon', (select jsonb_object_agg(horizon::text, jsonb_build_object(
        'observed', observed, 'unavailable', unavailable, 'pending', pending,
        'coverage', case when observed + unavailable > 0
                         then round(observed::numeric / (observed + unavailable), 4) end)) from hz),
    'invocations_today', (select coalesce(jsonb_object_agg(result, count), '{}'::jsonb)
        from ops.invocation_daily where day = (at at time zone 'UTC')::date),
    'invocations_yesterday', (select coalesce(jsonb_object_agg(result, count), '{}'::jsonb)
        from ops.invocation_daily where day = (at at time zone 'UTC')::date - 1)
  )
  $$;

-- Compact health at a given instant:
--   FAILING  the three most recent finished rounds all FAILED
--   STALE    no COMPLETED round finished within the last 3 minutes
--   OK       otherwise
create or replace function ops.recorder_health_at(at timestamptz) returns jsonb
  language sql stable security definer set search_path = ''
  as $$
  with fin as (
    select state from history.signal_round
    where state in ('COMPLETED', 'FAILED') and scheduled_at <= at
    order by scheduled_at desc limit 3
  ),
  s as (select ops.recorder_status_at(at) as j)
  select jsonb_build_object(
    'status', case
      when (select count(*) from fin) = 3 and (select bool_and(state = 'FAILED') from fin) then 'FAILING'
      when (s.j ->> 'last_completed_finished_at') is null
        or (s.j ->> 'last_completed_finished_at')::timestamptz < at - interval '3 minutes' then 'STALE'
      else 'OK' end,
    'at', at,
    'last_scheduled_round', s.j -> 'last_scheduled_round',
    'last_completed_round', s.j -> 'last_completed_round',
    'last_completed_finished_at', s.j -> 'last_completed_finished_at',
    'last_failed_round', s.j -> 'last_failed_round',
    'rounds_60m', s.j -> 'rounds_60m',
    'last_provider_success', s.j -> 'last_provider_success',
    'last_rate_limited', s.j -> 'last_rate_limited',
    'duration_ms_24h', s.j -> 'duration_ms_24h',
    'database_bytes', s.j -> 'database_bytes',
    'open_episodes', s.j -> 'open_episodes',
    'events_total', s.j -> 'events_total',
    'outcomes', s.j -> 'outcomes')
  from s
  $$;

create view ops.recorder_status as select ops.recorder_status_at(now()) as status;
create view ops.recorder_health as select ops.recorder_health_at(now()) as health;

-- Housekeeping (scheduled daily by the B0 cron script):
--   • ops.invocation_daily older than 30 days
--   • pg_cron run history (cron.job_run_details is never cleaned automatically)
--     older than 7 days, when pg_cron is installed
-- pg_net responses (net._http_response) expire on their own (pg_net.ttl, 6 h default).
create or replace function ops.prune_housekeeping(at timestamptz default now()) returns jsonb
  language plpgsql
  as $$
declare
  inv integer := 0;
  runs integer := 0;
begin
  delete from ops.invocation_daily where day < (at at time zone 'UTC')::date - 30;
  get diagnostics inv = row_count;
  if to_regclass('cron.job_run_details') is not null then
    execute 'delete from cron.job_run_details where end_time < $1' using at - interval '7 days';
    get diagnostics runs = row_count;
  end if;
  return jsonb_build_object('invocation_daily', inv, 'cron_job_run_details', runs);
end
$$;

-- ---------------------------------------------------------------------------
-- Roles and privileges (least privilege; browser roles get nothing)
-- ---------------------------------------------------------------------------
do $$
begin
  begin
    create role recorder_writer nologin;
  exception when duplicate_object then null;
  end;
  begin
    create role recorder_reader nologin;
  exception when duplicate_object then null;
  end;
end
$$;

revoke all on schema history, engine, ops from public;
revoke all on all tables in schema history, engine, ops from public;
revoke all on all functions in schema history, engine, ops from public;

do $$
declare
  r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on schema history, engine, ops from %I', r);
      execute format('revoke all on all tables in schema history, engine, ops from %I', r);
      execute format('revoke all on all functions in schema history, engine, ops from %I', r);
    end if;
  end loop;
end
$$;

-- recorder_writer: exactly what the recorder's store needs.
grant usage on schema history, engine, ops to recorder_writer;
grant select, insert                 on history.signal_event    to recorder_writer;  -- immutable
grant select, insert, update         on history.signal_episode  to recorder_writer;  -- CAS updates
grant select, insert                 on history.signal_outcome  to recorder_writer;  -- insert-only
grant select, insert, update, delete on history.signal_round    to recorder_writer;  -- claim / commit / prune
grant select, insert, update, delete on engine.snapshot_round, engine.pending_outcome,
                                        engine.provider_cooldown to recorder_writer;
grant select, insert, update         on ops.invocation_daily    to recorder_writer;
grant execute on function engine.ms_to_ts(bigint), engine.ts_to_ms(timestamptz) to recorder_writer;

-- recorder_reader: the health endpoint — status functions only, no table access.
grant usage on schema ops to recorder_reader;
grant execute on function ops.recorder_status_at(timestamptz), ops.recorder_health_at(timestamptz)
  to recorder_reader;
grant select on ops.recorder_status, ops.recorder_health to recorder_reader;
